### ISSUE TITLE
Fix Travis configuration

### ISSUE THREAD

**Issue by Ecarrion** [Automattic/WordPressComKit#17]
Currently Travis is trying to build the project with `xctool` which doesn't know how to build a swift project, also Xcode 7.3 is being used who doesn't support Swift 2.3

**Comment by sendhil** [comment]
We've been using Buddybuild for our other projects, we should just drop Travis and swap over to that.

**Comment by sendhil** [comment]
https://github.com/Automattic/WordPressComKit/issues/19

**Comment by sendhil** [comment]
Let's close this in favor of #19. Thanks for the h/t @Ecarrion.
